apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fun
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fun
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
